# Continuous Integration pipeline

trigger:
  batch: false
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pr:
  autoCancel: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

schedules:
- cron: '0 0 * * *'
  displayName: 'Daily midnight build'
  branches:
    include:
    - main
  always: true

variables:
- group: 'build-tools'
- name: 'dotnet.sdk.version'
  value: '5.0.101'
- name: 'dotnet.build.configuration'
  value: 'Debug'
- name: 'dotnet.solution.file'
  value: 'Dotnet50Samples.sln'

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Get .NET SDK $(dotnet.sdk.version)'
  inputs:
    packageType: 'sdk'
    version: $(dotnet.sdk.version)
- task: DotNetCoreCLI@2
  displayName: 'Restore .NET packages'
  inputs:
    command: 'restore'
    projects: $(dotnet.solution.file)
    feedsToUse: 'select'
    noCache: $(dotnet.cache.disable)
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    COREHOST_TRACE: 0
- task: DotNetCoreCLI@2
  displayName: 'Build .NET solution'
  inputs:
    command: 'build'
    projects: $(dotnet.solution.file)
    arguments: '--no-restore -c $(dotnet.build.configuration)'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    COREHOST_TRACE: 0
